use_frameworks!

platform :ios, '8.0'

target 'TMExtension_Example' do
  pod 'TMExtension', :path => '../'

  target 'TMExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
